apiVersion: v1
kind: Service
metadata:
  name: {{ include "hellojenkins-chart.fullname" . }}
  labels:
{{ include "hellojenkins-chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort  }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app.kubernetes.io/name: {{ include "hellojenkins-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
